import { useMemo } from 'react';
import * as THREE from 'three';
import { HALF, TERRAIN_SIZE, getHeight, getHeightRange } from '../utils/terrainHeight';

/**
 * Topographic contour lines generated by marching squares over a height grid.
 * Each line traces a constant elevation and is draped onto the surface (its Y
 * equals the contour level, so it sits on the ground). Every 4th line is an
 * "index contour" drawn brighter, exactly as on a real topographic map.
 */

const GRID = 180; // sampling resolution per side
const INTERVAL = 3; // metres between contours
const INDEX_EVERY = 4; // every Nth contour is emphasised

// Authored in sRGB (warm dark-brown linework like a printed topo map), stored
// linear to match the rest of the scene.
const NORMAL_COLOR = new THREE.Color().setRGB(0.22, 0.17, 0.12, THREE.SRGBColorSpace);
const INDEX_COLOR = new THREE.Color().setRGB(0.8, 0.7, 0.47, THREE.SRGBColorSpace);

function buildGeometry(): THREE.BufferGeometry {
  const { min, max } = getHeightRange();
  const step = TERRAIN_SIZE / GRID;

  // Precompute the height grid once.
  const h: number[] = new Array((GRID + 1) * (GRID + 1));
  for (let iz = 0; iz <= GRID; iz++) {
    for (let ix = 0; ix <= GRID; ix++) {
      const x = -HALF + ix * step;
      const z = -HALF + iz * step;
      h[iz * (GRID + 1) + ix] = getHeight(x, z);
    }
  }
  const H = (ix: number, iz: number) => h[iz * (GRID + 1) + ix];

  const positions: number[] = [];
  const colors: number[] = [];

  const firstLevel = Math.ceil(min / INTERVAL) * INTERVAL;
  let levelIndex = Math.round(firstLevel / INTERVAL);

  for (let level = firstLevel; level <= max; level += INTERVAL, levelIndex++) {
    const isIndex = levelIndex % INDEX_EVERY === 0;
    const c = isIndex ? INDEX_COLOR : NORMAL_COLOR;
    const y = level + 0.06; // tiny lift to avoid z-fighting with the mesh

    for (let iz = 0; iz < GRID; iz++) {
      for (let ix = 0; ix < GRID; ix++) {
        const x0 = -HALF + ix * step;
        const z0 = -HALF + iz * step;
        const x1 = x0 + step;
        const z1 = z0 + step;
        const h0 = H(ix, iz); // P0 (x0,z0)
        const h1 = H(ix + 1, iz); // P1 (x1,z0)
        const h2 = H(ix + 1, iz + 1); // P2 (x1,z1)
        const h3 = H(ix, iz + 1); // P3 (x0,z1)

        // Collect edge crossings for this level.
        const pts: number[] = []; // pairs of (x, z)
        const edge = (
          ha: number,
          hb: number,
          xa: number,
          za: number,
          xb: number,
          zb: number,
        ) => {
          if (ha < level !== hb < level && ha !== hb) {
            const t = (level - ha) / (hb - ha);
            pts.push(xa + (xb - xa) * t, za + (zb - za) * t);
          }
        };
        edge(h0, h1, x0, z0, x1, z0); // bottom
        edge(h1, h2, x1, z0, x1, z1); // right
        edge(h2, h3, x1, z1, x0, z1); // top
        edge(h3, h0, x0, z1, x0, z0); // left

        const pushSeg = (a: number, b: number) => {
          positions.push(pts[a], y, pts[a + 1], pts[b], y, pts[b + 1]);
          colors.push(c.r, c.g, c.b, c.r, c.g, c.b);
        };
        if (pts.length === 4) {
          pushSeg(0, 2);
        } else if (pts.length === 8) {
          // Ambiguous saddle cell: connect crossings pairwise.
          pushSeg(0, 2);
          pushSeg(4, 6);
        }
      }
    }
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geo.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
  return geo;
}

export default function ContourLines({ visible }: { visible: boolean }) {
  const geometry = useMemo(buildGeometry, []);

  return (
    <lineSegments geometry={geometry} visible={visible} frustumCulled={false}>
      <lineBasicMaterial vertexColors transparent opacity={0.5} toneMapped={false} />
    </lineSegments>
  );
}
